---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-flagd
spec:
  type: ClusterIP
  ports:
    - port: 8013
      name: tcp-service
      targetPort: 8013
  selector:
    opentelemetry.io/name: opentelemetry-demo-flagd
