---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-adservice
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: 8080
  selector:
    opentelemetry.io/name: opentelemetry-demo-adservice
